---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract WordPress archive
  unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv
    remote_src: True
    creates: /srv/wordpress

- name: Initialize WordPress folder
  command: cp -R /srv/wordpress /srv/{{ item['nginx_hostname'] }}
  args:
    creates: "/srv/{{ item['nginx_hostname'] }}"
  with_items: "{{ sites }}"

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Create WordPress database for site
  mysql_db: name={{ item['wp_db_name'] }} state=present
  with_items: "{{ sites }}"

- name: Create WordPress database user with appropriate access
  mysql_user: name={{ item['wp_db_user'] }} password={{ item['wp_db_password'] }} priv={{ item['wp_db_name'] }}.*:ALL host='localhost' state=present
  with_items: "{{ sites }}"

- name: Copy WordPress Live config file
  template: src=wp-config.php.j2 dest=/srv/{{ item['nginx_hostname'] }}/wp-config.php
  with_items: "{{ sites }}"

- name: Change ownership of Live WordPress installation
  file: path=/srv/{{ item['nginx_hostname'] }}/ owner=wordpress group=wordpress state=directory recurse=yes
  with_items: "{{ sites }}"

- name: install SEManage
  yum: pkg=policycoreutils-python state=present

- name: set the SELinux policy for the Live Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/{{ item['nginx_hostname'] }}(/.*)?"
  with_items: "{{ sites }}"

- name: set the SELinux policy for wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ item['nginx_hostname'] }}/wp-config\.php"
  with_items: "{{ sites }}"

- name: set the SELinux policy for wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ item['nginx_hostname'] }}/wp-content(/.*)?"
  with_items: "{{ sites }}"

- name: set the SELinux policy for the Live *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ item['nginx_hostname'] }}/.*\.php"
  with_items: "{{ sites }}"

- name: set the SELinux policy for the Live Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ item['nginx_hostname'] }}/wp-content/upgrade(/.*)?"
  with_items: "{{ sites }}"

- name: set the SELinux policy for the Live Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ item['nginx_hostname'] }}/wp-content/uploads(/.*)?"
  with_items: "{{ sites }}"

- name: set the SELinux policy for the Live wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ item['nginx_hostname'] }}/wp-includes/.*\.php"
  with_items: "{{ sites }}"

- name: set the SELinux on all the Live Files
  command: restorecon -Rv /srv/{{ item['nginx_hostname'] }}
  with_items: "{{ sites }}"

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
