---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract WordPress archive
  unarchive:
    src: /srv/wordpress-{{ wp_version }}.tar.gz
    dest: /srv
    remote_src: True
    creates: /srv/wordpress

- name: Initialize Live WordPress folder
  command: cp -R /srv/wordpress /srv/{{ server_hostname_live }}
  args:
    creates: "/srv/{{ server_hostname_live }}"

- name: Initialize Beta WordPress folder
  command: cp -R /srv/wordpress /srv/{{ server_hostname_beta }}
  args:
    creates: "/srv/{{ server_hostname_beta }}"

- name: Add group "wordpress"
  group: name=wordpress

- name: Add user "wordpress"
  user: name=wordpress group=wordpress home=/srv/{{ server_hostname_live }}/

- name: Fetch random salts for WordPress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no

- name: Create WordPress database for Live site
  mysql_db: name={{ wp_db_name_live }} state=present

- name: Create WordPress database for Beta site
  mysql_db: name={{ wp_db_name_beta }} state=present

- name: Create WordPress database user with access to Live and Beta
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name_live }}.*:ALL/{{ wp_db_name_beta }}.*:ALL host='localhost' state=present

- name: Copy WordPress Live config file
  template: src=wp-config.php.live.j2 dest=/srv/{{ server_hostname_live }}/wp-config.php

- name: Copy WordPress Beta config file
  template: src=wp-config.php.beta.j2 dest=/srv/{{ server_hostname_beta }}/wp-config.php

- name: Change ownership of Live WordPress installation
  file: path=/srv/{{ server_hostname_live }}/ owner=wordpress group=wordpress state=directory recurse=yes

- name: Change ownership of Beta WordPress installation
  file: path=/srv/{{ server_hostname_beta }}/ owner=wordpress group=wordpress state=directory recurse=yes

- name: install SEManage
  yum: pkg=policycoreutils-python state=present

- name: set the SELinux policy for the Live Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/{{ server_hostname_live }}(/.*)?"

- name: set the SELinux policy for the Beta Wordpress directory
  command: semanage fcontext -a -t httpd_sys_content_t "/srv/{{ server_hostname_beta }}(/.*)?"

- name: set the SELinux policy for Live wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_live }}/wp-config\.php"

- name: set the SELinux policy for Beta wp-config.php
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_beta }}/wp-config\.php"

- name: set the SELinux policy for Live wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_live }}/wp-content(/.*)?"

- name: set the SELinux policy for Beta wp-content directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_beta }}/wp-content(/.*)?"

- name: set the SELinux policy for the Live *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_live }}/.*\.php"

- name: set the SELinux policy for the Beta *.php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_beta }}/.*\.php"

- name: set the SELinux policy for the Live Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_live }}/wp-content/upgrade(/.*)?"

- name: set the SELinux policy for the Beta Upgrade directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_beta }}/wp-content/upgrade(/.*)?"

- name: set the SELinux policy for the Live Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_live }}/wp-content/uploads(/.*)?"

- name: set the SELinux policy for the Beta Uploads directory
  command: semanage fcontext -a -t httpd_sys_rw_content_t "/srv/{{ server_hostname_beta }}/wp-content/uploads(/.*)?"

- name: set the SELinux policy for the Live wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_live }}/wp-includes/.*\.php"

- name: set the SELinux policy for the Beta wp-includes php files
  command: semanage fcontext -a -t httpd_sys_script_exec_t "/srv/{{ server_hostname_beta }}/wp-includes/.*\.php"

- name: set the SELinux on all the Live Files
  command: restorecon -Rv /srv/{{ server_hostname_live }}

- name: set the SELinux on all the Beta Files
  command: restorecon -Rv /srv/{{ server_hostname_beta }}

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
